"""Compute a bounding box for each state's SVG path in src/nigeriaStates.ts.

Writes src/stateBounds.ts — STATE_BOUNDS[name] = [minX, minY, width, height] —
used to zoom the shared map into a single state on its page.

Run:  python frontend/scripts/state_bounds.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "nigeriaStates.ts"
OUT = ROOT / "src" / "stateBounds.ts"

NUM = r"-?\d*\.?\d+(?:[eE][-+]?\d+)?"
TOKEN = re.compile(rf"[A-Za-z]|{NUM}")


def bbox(d: str):
    toks = TOKEN.findall(d)
    xs: list[float] = []
    ys: list[float] = []
    i = 0
    cx = cy = sx = sy = 0.0
    cmd = ""

    def take() -> float:
        nonlocal i
        v = float(toks[i])
        i += 1
        return v

    while i < len(toks):
        if toks[i].isalpha():
            cmd = toks[i]
            i += 1
            if cmd in "Zz":
                cx, cy = sx, sy
                continue
        c = cmd
        if c in "Mm":
            x, y = take(), take()
            cx, cy = (cx + x, cy + y) if c == "m" else (x, y)
            sx, sy = cx, cy
            cmd = "l" if c == "m" else "L"  # implicit following pairs are line-tos
        elif c in "Ll":
            x, y = take(), take()
            cx, cy = (cx + x, cy + y) if c == "l" else (x, y)
        elif c in "Hh":
            x = take()
            cx = cx + x if c == "h" else x
        elif c in "Vv":
            y = take()
            cy = cy + y if c == "v" else y
        elif c in "Cc":
            p = [take() for _ in range(6)]
            pts = [(p[0], p[1]), (p[2], p[3]), (p[4], p[5])]
            if c == "c":
                pts = [(cx + a, cy + b) for a, b in pts]
            for a, b in pts:
                xs.append(a)
                ys.append(b)
            cx, cy = pts[-1]
            xs.append(cx)
            ys.append(cy)
            continue
        elif c in "SsQq":
            p = [take() for _ in range(4)]
            pts = [(p[0], p[1]), (p[2], p[3])]
            if c in "sq":
                pts = [(cx + a, cy + b) for a, b in pts]
            for a, b in pts:
                xs.append(a)
                ys.append(b)
            cx, cy = pts[-1]
            xs.append(cx)
            ys.append(cy)
            continue
        elif c in "Tt":
            x, y = take(), take()
            cx, cy = (cx + x, cy + y) if c == "t" else (x, y)
        elif c in "Aa":
            p = [take() for _ in range(7)]
            x, y = p[5], p[6]
            cx, cy = (cx + x, cy + y) if c == "a" else (x, y)
        else:
            i += 1
            continue
        xs.append(cx)
        ys.append(cy)

    return min(xs), min(ys), max(xs), max(ys)


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    pairs = re.findall(r"name:\s*'([^']*)',\s*d:\s*'([^']*)'", text, re.DOTALL)
    out = ["// Auto-generated by scripts/state_bounds.py — do not edit.",
           "export const STATE_BOUNDS: Record<string, [number, number, number, number]> = {"]
    for name, d in pairs:
        x0, y0, x1, y1 = bbox(d)
        out.append(f"  {name!r}: [{round(x0, 1)}, {round(y0, 1)}, {round(x1 - x0, 1)}, {round(y1 - y0, 1)}],")
    out.append("}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {len(pairs)} state bounds -> {OUT}")
    for name, d in pairs[:4]:
        print(f"  {name}: {bbox(d)}")


if __name__ == "__main__":
    main()
