/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SenatorsRouteImport } from './routes/senators'
import { Route as RepsRouteImport } from './routes/reps'
import { Route as ProblemUnitsRouteImport } from './routes/problem-units'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PoliticiansRouteImport } from './routes/politicians'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R2027RouteImport } from './routes/2027'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R2027IndexRouteImport } from './routes/2027.index'
import { Route as WardsStateRouteImport } from './routes/wards.$state'
import { Route as WardWardRouteImport } from './routes/ward.$ward'
import { Route as StatesStateRouteImport } from './routes/states.$state'
import { Route as PredictionIdRouteImport } from './routes/prediction.$id'
import { Route as PoliticianIdRouteImport } from './routes/politician.$id'
import { Route as PartyAcronymRouteImport } from './routes/party.$acronym'
import { Route as LgaIdRouteImport } from './routes/lga.$id'
import { Route as R2027SenateRouteImport } from './routes/2027.senate'
import { Route as R2027PresidentialRouteImport } from './routes/2027.presidential'
import { Route as R2027GovernorRouteImport } from './routes/2027.governor'
import { Route as StatesStateIndexRouteImport } from './routes/states.$state.index'
import { Route as R2027PresidentialIndexRouteImport } from './routes/2027.presidential.index'
import { Route as StatesStatePoliticiansRouteImport } from './routes/states.$state.politicians'
import { Route as StatesStateLgasRouteImport } from './routes/states.$state.lgas'
import { Route as R2027PresidentialStatesRouteImport } from './routes/2027.presidential.states'
import { Route as R2027PresidentialStatesIndexRouteImport } from './routes/2027.presidential.states.index'
import { Route as R2027PresidentialStatesStateRouteImport } from './routes/2027.presidential.states.$state'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SenatorsRoute = SenatorsRouteImport.update({
  id: '/senators',
  path: '/senators',
  getParentRoute: () => rootRouteImport,
} as any)
const RepsRoute = RepsRouteImport.update({
  id: '/reps',
  path: '/reps',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemUnitsRoute = ProblemUnitsRouteImport.update({
  id: '/problem-units',
  path: '/problem-units',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticiansRoute = PoliticiansRouteImport.update({
  id: '/politicians',
  path: '/politicians',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R2027Route = R2027RouteImport.update({
  id: '/2027',
  path: '/2027',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2027IndexRoute = R2027IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R2027Route,
} as any)
const WardsStateRoute = WardsStateRouteImport.update({
  id: '/wards/$state',
  path: '/wards/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const WardWardRoute = WardWardRouteImport.update({
  id: '/ward/$ward',
  path: '/ward/$ward',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateRoute = StatesStateRouteImport.update({
  id: '/states/$state',
  path: '/states/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionIdRoute = PredictionIdRouteImport.update({
  id: '/prediction/$id',
  path: '/prediction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticianIdRoute = PoliticianIdRouteImport.update({
  id: '/politician/$id',
  path: '/politician/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyAcronymRoute = PartyAcronymRouteImport.update({
  id: '/party/$acronym',
  path: '/party/$acronym',
  getParentRoute: () => rootRouteImport,
} as any)
const LgaIdRoute = LgaIdRouteImport.update({
  id: '/lga/$id',
  path: '/lga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const R2027SenateRoute = R2027SenateRouteImport.update({
  id: '/senate',
  path: '/senate',
  getParentRoute: () => R2027Route,
} as any)
const R2027PresidentialRoute = R2027PresidentialRouteImport.update({
  id: '/presidential',
  path: '/presidential',
  getParentRoute: () => R2027Route,
} as any)
const R2027GovernorRoute = R2027GovernorRouteImport.update({
  id: '/governor',
  path: '/governor',
  getParentRoute: () => R2027Route,
} as any)
const StatesStateIndexRoute = StatesStateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatesStateRoute,
} as any)
const R2027PresidentialIndexRoute = R2027PresidentialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R2027PresidentialRoute,
} as any)
const StatesStatePoliticiansRoute = StatesStatePoliticiansRouteImport.update({
  id: '/politicians',
  path: '/politicians',
  getParentRoute: () => StatesStateRoute,
} as any)
const StatesStateLgasRoute = StatesStateLgasRouteImport.update({
  id: '/lgas',
  path: '/lgas',
  getParentRoute: () => StatesStateRoute,
} as any)
const R2027PresidentialStatesRoute = R2027PresidentialStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => R2027PresidentialRoute,
} as any)
const R2027PresidentialStatesIndexRoute =
  R2027PresidentialStatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => R2027PresidentialStatesRoute,
  } as any)
const R2027PresidentialStatesStateRoute =
  R2027PresidentialStatesStateRouteImport.update({
    id: '/$state',
    path: '/$state',
    getParentRoute: () => R2027PresidentialStatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2027': typeof R2027RouteWithChildren
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/onboarding': typeof OnboardingRoute
  '/parties': typeof PartiesRoute
  '/politicians': typeof PoliticiansRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/problem-units': typeof ProblemUnitsRoute
  '/reps': typeof RepsRoute
  '/senators': typeof SenatorsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/2027/governor': typeof R2027GovernorRoute
  '/2027/presidential': typeof R2027PresidentialRouteWithChildren
  '/2027/senate': typeof R2027SenateRoute
  '/lga/$id': typeof LgaIdRoute
  '/party/$acronym': typeof PartyAcronymRoute
  '/politician/$id': typeof PoliticianIdRoute
  '/prediction/$id': typeof PredictionIdRoute
  '/states/$state': typeof StatesStateRouteWithChildren
  '/ward/$ward': typeof WardWardRoute
  '/wards/$state': typeof WardsStateRoute
  '/2027/': typeof R2027IndexRoute
  '/2027/presidential/states': typeof R2027PresidentialStatesRouteWithChildren
  '/states/$state/lgas': typeof StatesStateLgasRoute
  '/states/$state/politicians': typeof StatesStatePoliticiansRoute
  '/2027/presidential/': typeof R2027PresidentialIndexRoute
  '/states/$state/': typeof StatesStateIndexRoute
  '/2027/presidential/states/$state': typeof R2027PresidentialStatesStateRoute
  '/2027/presidential/states/': typeof R2027PresidentialStatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/onboarding': typeof OnboardingRoute
  '/parties': typeof PartiesRoute
  '/politicians': typeof PoliticiansRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/problem-units': typeof ProblemUnitsRoute
  '/reps': typeof RepsRoute
  '/senators': typeof SenatorsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/2027/governor': typeof R2027GovernorRoute
  '/2027/senate': typeof R2027SenateRoute
  '/lga/$id': typeof LgaIdRoute
  '/party/$acronym': typeof PartyAcronymRoute
  '/politician/$id': typeof PoliticianIdRoute
  '/prediction/$id': typeof PredictionIdRoute
  '/ward/$ward': typeof WardWardRoute
  '/wards/$state': typeof WardsStateRoute
  '/2027': typeof R2027IndexRoute
  '/states/$state/lgas': typeof StatesStateLgasRoute
  '/states/$state/politicians': typeof StatesStatePoliticiansRoute
  '/2027/presidential': typeof R2027PresidentialIndexRoute
  '/states/$state': typeof StatesStateIndexRoute
  '/2027/presidential/states/$state': typeof R2027PresidentialStatesStateRoute
  '/2027/presidential/states': typeof R2027PresidentialStatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2027': typeof R2027RouteWithChildren
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/onboarding': typeof OnboardingRoute
  '/parties': typeof PartiesRoute
  '/politicians': typeof PoliticiansRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/problem-units': typeof ProblemUnitsRoute
  '/reps': typeof RepsRoute
  '/senators': typeof SenatorsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/2027/governor': typeof R2027GovernorRoute
  '/2027/presidential': typeof R2027PresidentialRouteWithChildren
  '/2027/senate': typeof R2027SenateRoute
  '/lga/$id': typeof LgaIdRoute
  '/party/$acronym': typeof PartyAcronymRoute
  '/politician/$id': typeof PoliticianIdRoute
  '/prediction/$id': typeof PredictionIdRoute
  '/states/$state': typeof StatesStateRouteWithChildren
  '/ward/$ward': typeof WardWardRoute
  '/wards/$state': typeof WardsStateRoute
  '/2027/': typeof R2027IndexRoute
  '/2027/presidential/states': typeof R2027PresidentialStatesRouteWithChildren
  '/states/$state/lgas': typeof StatesStateLgasRoute
  '/states/$state/politicians': typeof StatesStatePoliticiansRoute
  '/2027/presidential/': typeof R2027PresidentialIndexRoute
  '/states/$state/': typeof StatesStateIndexRoute
  '/2027/presidential/states/$state': typeof R2027PresidentialStatesStateRoute
  '/2027/presidential/states/': typeof R2027PresidentialStatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2027'
    | '/admin'
    | '/contact'
    | '/contribute'
    | '/dashboard'
    | '/login'
    | '/methodology'
    | '/onboarding'
    | '/parties'
    | '/politicians'
    | '/predictions'
    | '/privacy'
    | '/problem-units'
    | '/reps'
    | '/senators'
    | '/signup'
    | '/team'
    | '/2027/governor'
    | '/2027/presidential'
    | '/2027/senate'
    | '/lga/$id'
    | '/party/$acronym'
    | '/politician/$id'
    | '/prediction/$id'
    | '/states/$state'
    | '/ward/$ward'
    | '/wards/$state'
    | '/2027/'
    | '/2027/presidential/states'
    | '/states/$state/lgas'
    | '/states/$state/politicians'
    | '/2027/presidential/'
    | '/states/$state/'
    | '/2027/presidential/states/$state'
    | '/2027/presidential/states/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/contribute'
    | '/dashboard'
    | '/login'
    | '/methodology'
    | '/onboarding'
    | '/parties'
    | '/politicians'
    | '/predictions'
    | '/privacy'
    | '/problem-units'
    | '/reps'
    | '/senators'
    | '/signup'
    | '/team'
    | '/2027/governor'
    | '/2027/senate'
    | '/lga/$id'
    | '/party/$acronym'
    | '/politician/$id'
    | '/prediction/$id'
    | '/ward/$ward'
    | '/wards/$state'
    | '/2027'
    | '/states/$state/lgas'
    | '/states/$state/politicians'
    | '/2027/presidential'
    | '/states/$state'
    | '/2027/presidential/states/$state'
    | '/2027/presidential/states'
  id:
    | '__root__'
    | '/'
    | '/2027'
    | '/admin'
    | '/contact'
    | '/contribute'
    | '/dashboard'
    | '/login'
    | '/methodology'
    | '/onboarding'
    | '/parties'
    | '/politicians'
    | '/predictions'
    | '/privacy'
    | '/problem-units'
    | '/reps'
    | '/senators'
    | '/signup'
    | '/team'
    | '/2027/governor'
    | '/2027/presidential'
    | '/2027/senate'
    | '/lga/$id'
    | '/party/$acronym'
    | '/politician/$id'
    | '/prediction/$id'
    | '/states/$state'
    | '/ward/$ward'
    | '/wards/$state'
    | '/2027/'
    | '/2027/presidential/states'
    | '/states/$state/lgas'
    | '/states/$state/politicians'
    | '/2027/presidential/'
    | '/states/$state/'
    | '/2027/presidential/states/$state'
    | '/2027/presidential/states/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2027Route: typeof R2027RouteWithChildren
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  ContributeRoute: typeof ContributeRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  OnboardingRoute: typeof OnboardingRoute
  PartiesRoute: typeof PartiesRoute
  PoliticiansRoute: typeof PoliticiansRoute
  PredictionsRoute: typeof PredictionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProblemUnitsRoute: typeof ProblemUnitsRoute
  RepsRoute: typeof RepsRoute
  SenatorsRoute: typeof SenatorsRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  LgaIdRoute: typeof LgaIdRoute
  PartyAcronymRoute: typeof PartyAcronymRoute
  PoliticianIdRoute: typeof PoliticianIdRoute
  PredictionIdRoute: typeof PredictionIdRoute
  StatesStateRoute: typeof StatesStateRouteWithChildren
  WardWardRoute: typeof WardWardRoute
  WardsStateRoute: typeof WardsStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senators': {
      id: '/senators'
      path: '/senators'
      fullPath: '/senators'
      preLoaderRoute: typeof SenatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reps': {
      id: '/reps'
      path: '/reps'
      fullPath: '/reps'
      preLoaderRoute: typeof RepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-units': {
      id: '/problem-units'
      path: '/problem-units'
      fullPath: '/problem-units'
      preLoaderRoute: typeof ProblemUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicians': {
      id: '/politicians'
      path: '/politicians'
      fullPath: '/politicians'
      preLoaderRoute: typeof PoliticiansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2027': {
      id: '/2027'
      path: '/2027'
      fullPath: '/2027'
      preLoaderRoute: typeof R2027RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2027/': {
      id: '/2027/'
      path: '/'
      fullPath: '/2027/'
      preLoaderRoute: typeof R2027IndexRouteImport
      parentRoute: typeof R2027Route
    }
    '/wards/$state': {
      id: '/wards/$state'
      path: '/wards/$state'
      fullPath: '/wards/$state'
      preLoaderRoute: typeof WardsStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ward/$ward': {
      id: '/ward/$ward'
      path: '/ward/$ward'
      fullPath: '/ward/$ward'
      preLoaderRoute: typeof WardWardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$state': {
      id: '/states/$state'
      path: '/states/$state'
      fullPath: '/states/$state'
      preLoaderRoute: typeof StatesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction/$id': {
      id: '/prediction/$id'
      path: '/prediction/$id'
      fullPath: '/prediction/$id'
      preLoaderRoute: typeof PredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politician/$id': {
      id: '/politician/$id'
      path: '/politician/$id'
      fullPath: '/politician/$id'
      preLoaderRoute: typeof PoliticianIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$acronym': {
      id: '/party/$acronym'
      path: '/party/$acronym'
      fullPath: '/party/$acronym'
      preLoaderRoute: typeof PartyAcronymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lga/$id': {
      id: '/lga/$id'
      path: '/lga/$id'
      fullPath: '/lga/$id'
      preLoaderRoute: typeof LgaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2027/senate': {
      id: '/2027/senate'
      path: '/senate'
      fullPath: '/2027/senate'
      preLoaderRoute: typeof R2027SenateRouteImport
      parentRoute: typeof R2027Route
    }
    '/2027/presidential': {
      id: '/2027/presidential'
      path: '/presidential'
      fullPath: '/2027/presidential'
      preLoaderRoute: typeof R2027PresidentialRouteImport
      parentRoute: typeof R2027Route
    }
    '/2027/governor': {
      id: '/2027/governor'
      path: '/governor'
      fullPath: '/2027/governor'
      preLoaderRoute: typeof R2027GovernorRouteImport
      parentRoute: typeof R2027Route
    }
    '/states/$state/': {
      id: '/states/$state/'
      path: '/'
      fullPath: '/states/$state/'
      preLoaderRoute: typeof StatesStateIndexRouteImport
      parentRoute: typeof StatesStateRoute
    }
    '/2027/presidential/': {
      id: '/2027/presidential/'
      path: '/'
      fullPath: '/2027/presidential/'
      preLoaderRoute: typeof R2027PresidentialIndexRouteImport
      parentRoute: typeof R2027PresidentialRoute
    }
    '/states/$state/politicians': {
      id: '/states/$state/politicians'
      path: '/politicians'
      fullPath: '/states/$state/politicians'
      preLoaderRoute: typeof StatesStatePoliticiansRouteImport
      parentRoute: typeof StatesStateRoute
    }
    '/states/$state/lgas': {
      id: '/states/$state/lgas'
      path: '/lgas'
      fullPath: '/states/$state/lgas'
      preLoaderRoute: typeof StatesStateLgasRouteImport
      parentRoute: typeof StatesStateRoute
    }
    '/2027/presidential/states': {
      id: '/2027/presidential/states'
      path: '/states'
      fullPath: '/2027/presidential/states'
      preLoaderRoute: typeof R2027PresidentialStatesRouteImport
      parentRoute: typeof R2027PresidentialRoute
    }
    '/2027/presidential/states/': {
      id: '/2027/presidential/states/'
      path: '/'
      fullPath: '/2027/presidential/states/'
      preLoaderRoute: typeof R2027PresidentialStatesIndexRouteImport
      parentRoute: typeof R2027PresidentialStatesRoute
    }
    '/2027/presidential/states/$state': {
      id: '/2027/presidential/states/$state'
      path: '/$state'
      fullPath: '/2027/presidential/states/$state'
      preLoaderRoute: typeof R2027PresidentialStatesStateRouteImport
      parentRoute: typeof R2027PresidentialStatesRoute
    }
  }
}

interface R2027PresidentialStatesRouteChildren {
  R2027PresidentialStatesStateRoute: typeof R2027PresidentialStatesStateRoute
  R2027PresidentialStatesIndexRoute: typeof R2027PresidentialStatesIndexRoute
}

const R2027PresidentialStatesRouteChildren: R2027PresidentialStatesRouteChildren =
  {
    R2027PresidentialStatesStateRoute: R2027PresidentialStatesStateRoute,
    R2027PresidentialStatesIndexRoute: R2027PresidentialStatesIndexRoute,
  }

const R2027PresidentialStatesRouteWithChildren =
  R2027PresidentialStatesRoute._addFileChildren(
    R2027PresidentialStatesRouteChildren,
  )

interface R2027PresidentialRouteChildren {
  R2027PresidentialStatesRoute: typeof R2027PresidentialStatesRouteWithChildren
  R2027PresidentialIndexRoute: typeof R2027PresidentialIndexRoute
}

const R2027PresidentialRouteChildren: R2027PresidentialRouteChildren = {
  R2027PresidentialStatesRoute: R2027PresidentialStatesRouteWithChildren,
  R2027PresidentialIndexRoute: R2027PresidentialIndexRoute,
}

const R2027PresidentialRouteWithChildren =
  R2027PresidentialRoute._addFileChildren(R2027PresidentialRouteChildren)

interface R2027RouteChildren {
  R2027GovernorRoute: typeof R2027GovernorRoute
  R2027PresidentialRoute: typeof R2027PresidentialRouteWithChildren
  R2027SenateRoute: typeof R2027SenateRoute
  R2027IndexRoute: typeof R2027IndexRoute
}

const R2027RouteChildren: R2027RouteChildren = {
  R2027GovernorRoute: R2027GovernorRoute,
  R2027PresidentialRoute: R2027PresidentialRouteWithChildren,
  R2027SenateRoute: R2027SenateRoute,
  R2027IndexRoute: R2027IndexRoute,
}

const R2027RouteWithChildren = R2027Route._addFileChildren(R2027RouteChildren)

interface StatesStateRouteChildren {
  StatesStateLgasRoute: typeof StatesStateLgasRoute
  StatesStatePoliticiansRoute: typeof StatesStatePoliticiansRoute
  StatesStateIndexRoute: typeof StatesStateIndexRoute
}

const StatesStateRouteChildren: StatesStateRouteChildren = {
  StatesStateLgasRoute: StatesStateLgasRoute,
  StatesStatePoliticiansRoute: StatesStatePoliticiansRoute,
  StatesStateIndexRoute: StatesStateIndexRoute,
}

const StatesStateRouteWithChildren = StatesStateRoute._addFileChildren(
  StatesStateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2027Route: R2027RouteWithChildren,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  ContributeRoute: ContributeRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  OnboardingRoute: OnboardingRoute,
  PartiesRoute: PartiesRoute,
  PoliticiansRoute: PoliticiansRoute,
  PredictionsRoute: PredictionsRoute,
  PrivacyRoute: PrivacyRoute,
  ProblemUnitsRoute: ProblemUnitsRoute,
  RepsRoute: RepsRoute,
  SenatorsRoute: SenatorsRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  LgaIdRoute: LgaIdRoute,
  PartyAcronymRoute: PartyAcronymRoute,
  PoliticianIdRoute: PoliticianIdRoute,
  PredictionIdRoute: PredictionIdRoute,
  StatesStateRoute: StatesStateRouteWithChildren,
  WardWardRoute: WardWardRoute,
  WardsStateRoute: WardsStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
